#!/usr/bin/env bash
# This script will loop from 1-10 and display "Best School' for all iteration except for the 4th and 8th iterations

counter=1
while [ $counter -le 10 ]
do
if [ $counter -eq 4 ]
then
echo "bad luck"
elif [ $counter -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((counter++))
done