#!/usr/bin/env bash
# Set up an Ubuntu server as follows:
# Set up localhost resolves to 127.0.0.2
# Set up facebook resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

cp -f ~/host.new /etc/hosts
